# Generated by Django 3.1.1 on 2021-10-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energencynumber',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energencynumber',
            name='number2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energencynumber',
            name='number3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
