# Generated by Django 3.1.1 on 2021-10-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendtoaccess',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.friendadd'),
        ),
    ]
