# Generated by Django 3.2.9 on 2021-11-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='trigger',
            field=models.IntegerField(default=0),
        ),
    ]
