# Generated by Django 3.1.1 on 2021-10-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymanaccess',
            name='d_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices'),
        ),
    ]
