# Generated by Django 3.1.7 on 2021-04-27 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H1sensor', models.FloatField(null=True)),
                ('H2sensor', models.FloatField(null=True)),
                ('H3sensor', models.FloatField(null=True)),
                ('H4sensor', models.FloatField(null=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
