# Generated by Django 3.1.1 on 2021-10-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allemail',
            name='id',
        ),
        migrations.AlterField(
            model_name='allemail',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.allemail'),
        ),
    ]
