# Generated by Django 3.1.1 on 2021-10-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20211028_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymanaccess',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.allemail', unique=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='emoji',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='location',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='message',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='ring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='s_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='song',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='trigger',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
