# Generated by Django 3.1.1 on 2021-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20211017_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendtoaccess',
            name='email',
        ),
        migrations.AddField(
            model_name='friendtoaccess',
            name='email',
            field=models.ManyToManyField(default='ok', to='newapp.friendadd'),
        ),
    ]
