# Generated by Django 3.1.1 on 2021-10-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20211027_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedsetup',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
