# Generated by Django 4.1.5 on 2023-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='timing',
            field=models.CharField(default='00:00', max_length=200),
        ),
    ]
