# Generated by Django 3.1.1 on 2021-10-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20211027_0605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
