# Generated by Django 3.1.1 on 2021-10-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_friendadd_friendlist_friendrequest_friendtoaccess_userimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
