# Generated by Django 3.1.1 on 2021-10-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20211028_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymanaccess',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.allemail'),
        ),
    ]
