# Generated by Django 3.1.7 on 2021-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_ssidpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='H1sensor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='health',
            name='H2sensor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='health',
            name='H3sensor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='health',
            name='H4sensor',
            field=models.FloatField(default=0.0),
        ),
    ]
