# Generated by Django 3.1.1 on 2021-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_familymanaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedsetup',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
