# Generated by Django 3.1.1 on 2021-10-14 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0004_auto_20211014_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='allDevices',
            fields=[
                ('d_id', models.CharField(default=0, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='emergencyNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.BigIntegerField(blank=True, null=True)),
                ('number2', models.BigIntegerField(blank=True, null=True)),
                ('number3', models.BigIntegerField(blank=True, null=True)),
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='energencyNumber',
        ),
        migrations.AlterField(
            model_name='device',
            name='d_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='d_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='d_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices'),
        ),
        migrations.AlterField(
            model_name='ssidpassword',
            name='d_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices'),
        ),
    ]
