# Generated by Django 3.1.1 on 2021-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20211028_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymanaccess',
            old_name='email1',
            new_name='sender_email',
        ),
        migrations.RenameField(
            model_name='friendtoaccess',
            old_name='email1',
            new_name='sender_email',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='email1',
            new_name='sender_email',
        ),
        migrations.AddField(
            model_name='familymanaccess',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
