# Generated by Django 3.1.1 on 2021-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20211029_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='trigger',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
