# Generated by Django 3.1.1 on 2021-10-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20211028_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymanaccess',
            name='d_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newapp.device'),
        ),
    ]
