# Generated by Django 4.1.5 on 2023-05-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
