# Generated by Django 4.1.5 on 2023-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=1, upload_to='usermessages/file/'),
            preserve_default=False,
        ),
    ]
