# Generated by Django 3.1.1 on 2021-10-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20211030_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedsetup',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='s_id',
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='message',
            field=models.TextField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='trigger',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
