# Generated by Django 3.1.1 on 2021-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20211031_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedsetup',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='emoji',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='location',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='message',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='ring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='song',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receivedsetup',
            name='trigger',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
