# Generated by Django 3.1.1 on 2021-11-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20211031_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencynumber',
            name='user',
        ),
    ]
