# Generated by Django 3.2.9 on 2021-11-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_remove_emergencynumber_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymanaccess',
            old_name='d_id',
            new_name='d_id_sender',
        ),
        migrations.AddField(
            model_name='familymanaccess',
            name='d_id_receiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='d_id_receiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='d_id_sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices'),
        ),
        migrations.CreateModel(
            name='SOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=199, null=True)),
                ('message', models.CharField(blank=True, max_length=99, null=True)),
                ('ring', models.IntegerField(blank=True, null=True)),
                ('user1', models.CharField(blank=True, max_length=50, null=True)),
                ('user2', models.CharField(blank=True, max_length=50, null=True)),
                ('user3', models.CharField(blank=True, max_length=50, null=True)),
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.alldevices')),
            ],
        ),
    ]
