# Generated by Django 3.1.7 on 2021-04-29 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(max_length=20, unique=True)),
                ('d_name', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ssidPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid1', models.CharField(max_length=15, unique=True)),
                ('password1', models.CharField(max_length=50)),
                ('ssid2', models.CharField(max_length=15, unique=True)),
                ('password2', models.CharField(max_length=50)),
                ('ssid3', models.CharField(max_length=15, unique=True)),
                ('password3', models.CharField(max_length=50)),
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.device')),
            ],
        ),
        migrations.CreateModel(
            name='setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=20, unique=True)),
                ('trigger', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=15)),
                ('ring', models.IntegerField()),
                ('message', models.TextField(max_length=999)),
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='healthrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthS1', models.FloatField(blank=True, null=True)),
                ('healthS2', models.FloatField(blank=True, null=True)),
                ('healthS3', models.FloatField(blank=True, null=True)),
                ('healthS4', models.FloatField(blank=True, null=True)),
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.device')),
            ],
        ),
    ]
